#!/usr/bin/env bash
set -Eeuo pipefail

# This helper configures the HTTP CONNECT path only. It never installs a
# certificate, CA, HTTPS proxy listener, or endpoint TLS interception.
PROXY_HOST="${GROUPROXY_PROXY_HOST:-proxy.corp.internal}"
PROXY_PORT="${GROUPROXY_PROXY_PORT:-80}"
NO_PROXY_VALUE="${GROUPROXY_NO_PROXY:-localhost,127.0.0.1,::1,.corp.internal,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}"

persist=true
system_scope=false
uninstall=false
desktop=true

usage() {
  cat <<'EOF'
Usage: linux-setup-proxy.sh [--persist] [--system] [--no-desktop] [--uninstall]

Configures the HTTP CONNECT proxy for the current user by default. --system
requires root and writes shell/environment defaults only; desktop settings
remain per-user. --uninstall removes only Grouproxy-managed settings.
EOF
}

for argument in "$@"; do
  case "$argument" in
    --persist) persist=true ;;
    --system) system_scope=true ;;
    --no-desktop) desktop=false ;;
    --uninstall) uninstall=true ;;
    --help|-h) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$argument" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ ! "$PROXY_HOST" =~ ^[A-Za-z0-9.-]+$ ]]; then
  printf 'GROUPROXY_PROXY_HOST is invalid.\n' >&2
  exit 2
fi
if [[ ! "$PROXY_PORT" =~ ^[0-9]+$ ]] || (( PROXY_PORT < 1 || PROXY_PORT > 65535 )); then
  printf 'GROUPROXY_PROXY_PORT must be between 1 and 65535.\n' >&2
  exit 2
fi
if [[ ! "$NO_PROXY_VALUE" =~ ^[A-Za-z0-9.,:/_-]+$ ]]; then
  printf 'GROUPROXY_NO_PROXY contains unsupported characters.\n' >&2
  exit 2
fi

if "$system_scope" && [[ "$EUID" -ne 0 ]]; then
  printf '%s\n' '--system requires root. Run the script without --system for a user setup.' >&2
  exit 2
fi

proxy_url="http://${PROXY_HOST}:${PROXY_PORT}"
export http_proxy="$proxy_url"
export https_proxy="$proxy_url"
export HTTP_PROXY="$proxy_url"
export HTTPS_PROXY="$proxy_url"
export no_proxy="$NO_PROXY_VALUE"
export NO_PROXY="$NO_PROXY_VALUE"

if "$system_scope"; then
  shell_file="/etc/profile.d/grouproxy-proxy.sh"
  environment_file="/etc/environment.d/90-grouproxy-proxy.conf"
else
  config_root="${XDG_CONFIG_HOME:-$HOME/.config}"
  shell_file="$config_root/grouproxy/proxy.env"
  environment_file="$config_root/environment.d/90-grouproxy-proxy.conf"
fi

write_managed_files() {
  mkdir -p "$(dirname "$shell_file")" "$(dirname "$environment_file")"
  umask 077
  {
    printf '# Generated by Grouproxy. Source this file in an existing shell.\n'
    printf 'export http_proxy=%q\n' "$http_proxy"
    printf 'export https_proxy=%q\n' "$https_proxy"
    printf 'export HTTP_PROXY=%q\n' "$HTTP_PROXY"
    printf 'export HTTPS_PROXY=%q\n' "$HTTPS_PROXY"
    printf 'export no_proxy=%q\n' "$no_proxy"
    printf 'export NO_PROXY=%q\n' "$NO_PROXY"
  } > "$shell_file"
  {
    printf '# Generated by Grouproxy. HTTP CONNECT only.\n'
    printf 'http_proxy=%s\n' "$http_proxy"
    printf 'https_proxy=%s\n' "$https_proxy"
    printf 'HTTP_PROXY=%s\n' "$HTTP_PROXY"
    printf 'HTTPS_PROXY=%s\n' "$HTTPS_PROXY"
    printf 'no_proxy=%s\n' "$no_proxy"
    printf 'NO_PROXY=%s\n' "$NO_PROXY"
  } > "$environment_file"
  if "$system_scope"; then
    chmod 0644 "$shell_file" "$environment_file"
  else
    chmod 0600 "$shell_file" "$environment_file"
  fi
}

reset_gnome_proxy() {
  command -v gsettings >/dev/null 2>&1 || return 0
  if ! gsettings reset org.gnome.system.proxy mode >/dev/null 2>&1; then
    printf 'GNOME settings were not available; reset them manually if needed.\n' >&2
    return 0
  fi
  for key in host port; do
    gsettings reset "org.gnome.system.proxy.http" "$key" >/dev/null 2>&1 || true
    gsettings reset "org.gnome.system.proxy.https" "$key" >/dev/null 2>&1 || true
  done
  gsettings reset org.gnome.system.proxy ignore-hosts >/dev/null 2>&1 || true
}

set_gnome_proxy() {
  command -v gsettings >/dev/null 2>&1 || {
    printf 'GNOME settings tool is unavailable; shell settings were still written.\n' >&2
    return 0
  }
  if gsettings set org.gnome.system.proxy mode manual >/dev/null 2>&1 &&
    gsettings set org.gnome.system.proxy.http host "$PROXY_HOST" >/dev/null 2>&1 &&
    gsettings set org.gnome.system.proxy.http port "$PROXY_PORT" >/dev/null 2>&1 &&
    gsettings set org.gnome.system.proxy.https host "$PROXY_HOST" >/dev/null 2>&1 &&
    gsettings set org.gnome.system.proxy.https port "$PROXY_PORT" >/dev/null 2>&1; then
    # gsettings expects a GVariant array. The fixed direct ranges make this
    # equivalent to the shell no_proxy defaults without embedding site IPs.
    gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.1', '::1', '*.corp.internal']" >/dev/null 2>&1 || true
    printf 'GNOME proxy settings were updated.\n'
  else
    printf 'GNOME settings were not available in this session; shell settings were still written.\n' >&2
  fi
}

kde_writer() {
  if command -v kwriteconfig6 >/dev/null 2>&1; then
    printf '%s\n' kwriteconfig6
  elif command -v kwriteconfig5 >/dev/null 2>&1; then
    printf '%s\n' kwriteconfig5
  fi
}

reset_kde_proxy() {
  local writer
  writer="$(kde_writer || true)"
  [[ -n "$writer" ]] || return 0
  "$writer" --file kioslaverc --group 'Proxy Settings' --key ProxyType 0 >/dev/null 2>&1 || true
  for key in httpProxy httpsProxy NoProxyFor; do
    "$writer" --file kioslaverc --group 'Proxy Settings' --key "$key" '' >/dev/null 2>&1 || true
  done
}

set_kde_proxy() {
  local writer
  writer="$(kde_writer || true)"
  [[ -n "$writer" ]] || {
    printf 'KDE settings tool is unavailable; shell settings were still written.\n' >&2
    return 0
  }
  if "$writer" --file kioslaverc --group 'Proxy Settings' --key ProxyType 1 &&
    "$writer" --file kioslaverc --group 'Proxy Settings' --key httpProxy "$PROXY_HOST $PROXY_PORT" &&
    "$writer" --file kioslaverc --group 'Proxy Settings' --key httpsProxy "$PROXY_HOST $PROXY_PORT" &&
    "$writer" --file kioslaverc --group 'Proxy Settings' --key NoProxyFor "$NO_PROXY_VALUE"; then
    printf 'KDE proxy settings were updated.\n'
  else
    printf 'KDE settings could not be updated; shell settings were still written.\n' >&2
  fi
}

if "$uninstall"; then
  rm -f "$shell_file" "$environment_file"
  if "$desktop" && [[ "${GROUPROXY_SKIP_DESKTOP:-0}" != "1" ]]; then
    reset_gnome_proxy
    reset_kde_proxy
  fi
  printf 'Removed Grouproxy-managed proxy settings.\n'
  exit 0
fi

if "$persist"; then
  write_managed_files
fi
if "$desktop" && [[ "${GROUPROXY_SKIP_DESKTOP:-0}" != "1" ]]; then
  if "$system_scope"; then
    printf 'System shell settings were updated; run without --system in each desktop session to update GNOME or KDE.\n' >&2
  else
    set_gnome_proxy
    set_kde_proxy
  fi
fi

printf 'HTTP CONNECT proxy configured at %s:%s\n' "$PROXY_HOST" "$PROXY_PORT"
printf 'Open a new session or source %s for the current shell.\n' "$shell_file"
printf 'HTTPS transport is intentionally disabled. Destination HTTPS remains end-to-end inside CONNECT.\n'
