"use client";

import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type PropsWithChildren,
} from "react";

export type Locale = "zh-CN" | "en" | "es";
export type Theme = "light" | "dark";

type Values = Record<string, string | number>;

const localeStorageKey = "grouproxy.locale";
const themeStorageKey = "grouproxy.theme";

const messages: Record<Locale, Record<string, string>> = {
  "zh-CN": {
    "Password": "密码",
    "GQuan code": "光圈验证码",
    "Create account": "注册账号",
    "Reset password": "重置密码",
    "Back to console": "返回控制台",
    "Control plane access": "控制平面访问",
    "IT code": "IT Code",
    "Verification code": "验证码",
    "Send code": "发送验证码",
    "Send again": "重新发送",
    "Sending...": "发送中...",
    "Working...": "处理中...",
    "Sign in": "登录",
    "Sign in with code": "验证码登录",
    "New password": "新密码",
    "Confirm password": "确认密码",
    "Verify your IT code before setting a password.": "请先验证 IT Code，再设置密码。",
    "Verify your IT code before choosing a new password.": "请先验证 IT Code，再设置新密码。",
    "Verification code sent through GQuan.": "验证码已通过光圈发送。",
    "Account registered. Sign in with the password you set.": "账号已注册，请使用刚设置的密码登录。",
    "Password reset. Sign in with the new password.": "密码已重置，请使用新密码登录。",
    "No active account is registered for this IT code.": "该 IT Code 尚未注册有效账号。",
    "GQuan verification delivery is unavailable.": "光圈验证码服务暂不可用。",
    "GQuan did not accept the verification request.": "光圈未接受本次验证码请求。",
    "GQuan verification quota is currently exhausted.": "光圈验证码配额暂时用尽。",
    "The IT code or password is not valid.": "IT Code 或密码不正确。",
    "Enter a valid IT code.": "请输入有效的 IT Code。",
    "Passwords must contain at least 12 characters.": "密码至少需要 12 个字符。",
    "This IT code already has an account.": "该 IT Code 已注册账号。",
    "The password confirmation does not match.": "两次输入的密码不一致。",
    "This code can no longer be used. Request another one.": "该验证码已失效，请重新获取。",
    "This verification code has expired. Request another one.": "验证码已过期，请重新获取。",
    "The verification code is not valid.": "验证码不正确。",
    "A code was sent recently. Wait before requesting another.": "验证码已发送，请稍后再试。",
    "Unable to reach the control plane. Check the local service and retry.": "无法连接控制平面，请检查本地服务后重试。",
    "The request contains invalid fields.": "请求字段不符合要求。",
    "The request could not be completed.": "请求未能完成。",
    "Language": "语言",
    "Switch to dark mode": "切换深色模式",
    "Switch to light mode": "切换浅色模式",
    "Close dialog": "关闭对话框",
    "Close details": "关闭详情",
    "Close navigation": "关闭导航",
    "Open navigation": "打开导航",
    "Refresh workspace": "刷新工作区",
    "Sign out": "退出登录",
    "Primary navigation": "主导航",
    "OPERATE": "运行",
    "POLICY": "策略",
    "DEPLOY": "部署",
    "GOVERN": "治理",
    "Overview": "概览",
    "Nodes": "节点",
    "Sites & CIDRs": "站点与网段",
    "Exceptions": "例外",
    "Cross-site": "跨站点",
    "Destination deny": "目标拒绝规则",
    "Subscriptions": "订阅",
    "Releases": "发布记录",
    "Tasks": "任务",
    "Audit": "审计",
    "Access": "访问",
    "Control plane": "控制平面",
    "HTTP only": "仅 HTTP",
    "Employee path": "员工通道",
    "Sign in required": "需要登录",
    "Use a control-plane administrator account to load operational data.": "请使用控制平面管理员账号加载运行数据。",
    "Unable to load this workspace": "无法加载此工作区",
    "Retry": "重试",
    "Loading": "加载中",
    "enabled": "已启用",
    "disabled": "已禁用",
    "online": "在线",
    "offline": "离线",
    "active": "活跃",
    "shutdown": "已关闭",
    "in sync": "已同步",
    "drift": "配置漂移",
    "pending": "等待中",
    "running": "执行中",
    "succeeded": "已完成",
    "failed": "失败",
    "queued": "排队中",
    "ready": "就绪",
    "published": "已发布",
    "current": "当前",
    "valid": "有效",
    "allowed": "允许",
    "denied": "拒绝",
    "Authentication method": "认证方式",
    "Account actions": "账号操作",
    "Cancel": "取消",
    "OPERATIONS": "运行态势",
    "SITE POLICY": "站点策略",
    "REGIONAL TOPOLOGY": "区域拓扑",
    "DEPLOYMENT": "部署",
    "EDGE INVENTORY": "边缘节点",
    "TASK QUEUE": "任务队列",
    "CURRENT PATH": "当前接入路径",
    "DEFAULT DENY": "默认拒绝",
    "SOURCE ACCESS": "来源访问",
    "POLICY TEST": "策略测试",
    "Actions": "操作",
    "Action": "动作",
    "Actor": "操作人",
    "Add": "添加",
    "Adding...": "添加中...",
    "Add CIDR": "添加 CIDR",
    "Add destination": "添加目标规则",
    "Add exception": "添加例外",
    "Add HTTP source": "添加 HTTP 源",
    "Advertise IP": "公告 IP",
    "After": "变更后",
    "All states": "全部状态",
    "Applied / desired": "已应用 / 目标版本",
    "Applied bundle matches": "已应用配置包一致",
    "Applied hash": "已应用哈希",
    "Audit event": "审计事件",
    "Audit chain is valid": "审计链有效",
    "Audit chain verification failed": "审计链校验失败",
    "Before": "变更前",
    "Chain origin": "链起点",
    "Check access": "检查访问",
    "Checking...": "检查中...",
    "CIDR is the current access boundary.": "CIDR 是当前访问边界。",
    "CIDR or IP": "CIDR 或 IP",
    "Column: destination listener": "列：目标监听器",
    "Comment": "备注",
    "Config": "配置",
    "Configuration": "配置",
    "Configuration in sync": "配置已同步",
    "Configuration or service state differs from the desired release.": "配置或服务状态与目标发布不一致。",
    "Control-plane summary": "控制平面摘要",
    "Copied": "已复制",
    "Copy": "复制",
    "Create draft": "创建草稿",
    "Created": "创建时间",
    "Delete destination": "删除目标规则",
    "Delete exception": "删除例外",
    "Details": "详情",
    "Disabled": "已禁用",
    "Domain": "域名",
    "Download": "下载",
    "Drift or failure": "漂移或失败",
    "Edge nodes": "边缘节点",
    "Enter an address to calculate the effective access policy.": "输入地址以计算生效访问策略。",
    "Error": "错误",
    "Expires": "到期时间",
    "Expires at": "到期于",
    "Filter node status": "筛选节点状态",
    "From \\ To": "来源 \\ 目标",
    "HTTPS proxy listener": "HTTPS 代理监听器",
    "Hash": "哈希",
    "Heartbeat": "心跳",
    "Heartbeat state": "心跳状态",
    "IP address": "IP 地址",
    "Immutable hash": "不可变哈希",
    "Inspect": "查看",
    "Invalid source IP.": "来源 IP 无效。",
    "Last error": "最近错误",
    "Last heartbeat": "最近心跳",
    "Lease": "租约",
    "Listener": "监听器",
    "Liveness": "存活状态",
    "Manage policy": "管理策略",
    "Monitor": "监控器",
    "Needs attention": "需要关注",
    "No active exceptions.": "当前没有生效例外。",
    "No destinations are blocked.": "当前没有被拒绝的目标。",
    "No effective CIDRs": "没有生效 CIDR",
    "No node enrolled": "没有已注册节点",
    "No site CIDRs configured.": "尚未配置站点 CIDR。",
    "Node": "节点",
    "Node inventory": "节点清单",
    "Node state": "节点状态",
    "Nodes online": "在线节点",
    "Office network": "办公网络",
    "Offline": "离线",
    "Online": "在线",
    "Open nodes": "打开节点",
    "Open policy": "打开策略",
    "Open queue": "打开队列",
    "Operator name": "操作人姓名",
    "Owner": "负责人",
    "Pattern": "匹配规则",
    "Policy changes require a release before nodes apply them.": "策略变更需要创建发布后才会由节点应用。",
    "Policy revision": "策略版本",
    "Previous hash": "上一个哈希",
    "Progress": "进度",
    "Proxy port": "代理端口",
    "Reason for block": "拦截原因",
    "Recent releases": "最近发布",
    "Request": "请求",
    "Requires operator review": "需要操作员复核",
    "Result": "结果",
    "Retries": "重试次数",
    "Review nodes": "查看节点",
    "Row: source site": "行：来源站点",
    "Sensitive values are redacted before storage.": "敏感值会在存储前脱敏。",
    "Service": "服务",
    "Setup script": "安装脚本",
    "Site": "站点",
    "Site CIDRs": "站点 CIDR",
    "Site authentication is also required.": "还需要站点身份验证。",
    "Site topology": "站点拓扑",
    "Source IP": "来源 IP",
    "Source IP preview": "来源 IP 预览",
    "Source-to-destination matrix": "来源到目标矩阵",
    "State": "状态",
    "Subscription": "订阅",
    "Target": "目标",
    "Task": "任务",
    "Time": "时间",
    "Travel approval reference": "出差审批编号",
    "Type": "类型",
    "Unknown site": "未知站点",
    "Updated": "更新时间",
    "Verify chain": "校验审计链",
    "Verifying...": "校验中...",
    "Version": "版本",
    "View": "查看",
    "View all": "查看全部",
    "this CIDR": "此 CIDR",
    "this exception": "此例外",
    "this pattern": "此规则",
    "this task": "此任务",
    "node": "节点",
    "nodes": "节点",
    "healthy": "健康",
    "degraded": "降级",
    "attention": "需要关注",
    "not enrolled": "未注册",
    "unhealthy": "不健康",
    "rollback failed": "回滚失败",
    "applying": "应用中",
    "health check": "健康检查",
    "rolling back": "回滚中",
    "rolled back": "已回滚",
    "cancel requested": "已请求取消",
    "expired": "已过期",
    "high": "高",
    "medium": "中",
    "low": "低",
    "draft": "草稿",
    "validated": "已校验",
    "release": "发布",
    "{action} {name}": "{action} {name}",
    "{count} events": "{count} 条事件",
    "{count} events checked": "已检查 {count} 条事件",
    "{count} local policy changes included in the next draft.": "下一个草稿将包含 {count} 项本地策略变更。",
    "{count} nodes": "{count} 个节点",
    "{count} nodes need attention": "{count} 个节点需要关注",
    "{count} queued or running tasks": "{count} 个排队或运行中的任务",
    "{count} sites": "{count} 个站点",
    "{name} CIDRs": "{name} 的 CIDR",
    "Policy revision v{revision} · HTTP :{port}": "策略版本 v{revision} · HTTP :{port}",
    "Allow {from} CIDRs to access {to}": "允许 {from} 的 CIDR 访问 {to}",
    "Add {from} source CIDRs to the effective access policy for {to}. This expands the destination listener's allowed network scope.": "将 {from} 的来源 CIDR 加入 {to} 的生效访问策略。这会扩大目标监听器允许的网络范围。",
    "Block the proxy listener for {name}. This changes desired policy and requires a release to reach its edge nodes.": "阻断 {name} 的代理监听器。这会变更目标策略，需发布后才能下发至边缘节点。",
    "Restore proxy listener access for {name}. A release is still required for monitors to apply the state.": "恢复 {name} 的代理监听器访问。监控器仍需通过发布才能应用此状态。",
    "Delete {value}": "删除 {value}",
    "Remove {value}": "移除 {value}",
    "Remove {value}. The next release for each site will exclude it from effective source access.": "移除 {value}。各站点的下一次发布将不再把它加入生效来源访问。",
    "Remove {value} from the global deny policy. New releases will no longer include it.": "从全局拒绝策略移除 {value}。后续发布将不再包含它。",
    "Remove {cidr} from {site}. The change remains local to the control plane until a release succeeds.": "从 {site} 移除 {cidr}。在发布成功前，此变更仅保留在控制平面。",
    "Request cancellation for {task}. Running work stops at its next safe checkpoint.": "请求取消 {task}。运行中的工作会在下一个安全检查点停止。",
    "Destination HTTPS remains end-to-end inside the HTTP CONNECT tunnel.": "目标 HTTPS 在 HTTP CONNECT 隧道内始终保持端到端加密。",
    "The control plane did not respond.": "控制平面未响应。",
    "Unable to load sites.": "无法加载站点。",
    "Unable to load CIDRs.": "无法加载 CIDR。",
    "This site does not exist.": "该站点不存在。",
    "The policy change was not accepted.": "策略变更未被接受。",
    "The exception was not accepted.": "例外规则未被接受。",
    "The cross-site policy was not accepted.": "跨站点策略未被接受。",
    "The destination policy was not accepted.": "目标策略未被接受。",
    "Unable to load cross-site access.": "无法加载跨站点访问策略。",
    "Unable to load the destination deny list.": "无法加载目标拒绝列表。",
    "Unable to load tasks.": "无法加载任务。",
    "The task could not be cancelled.": "无法取消任务。",
    "Audit verification failed.": "审计校验失败。",
    "Unable to load audit events.": "无法加载审计事件。",
    "Unable to render the Linux setup script.": "无法生成 Linux 安装脚本。",
    "network_error": "无法连接控制平面。",
    "request_failed": "请求未能完成。",
    "invalid_cidr": "CIDR 格式无效。",
    "cidr_exists": "该 CIDR 已存在。",
    "invalid_source_ip": "来源 IP 无效。",
    "exception_must_expire_in_future": "例外到期时间必须在未来。",
    "invalid_exception": "例外规则无效。",
    "invalid_blacklist_pattern": "目标规则无效。",
    "blacklist_entry_exists": "该目标规则已存在。",
    "1 hour": "1 小时",
    "6 hours": "6 小时",
    "24 hours": "24 小时",
    "ACK status": "ACK 状态",
    "Active deployments": "活动部署",
    "Active work": "活动工作",
    "Awaiting node ACK": "等待节点 ACK",
    "Content hash": "内容哈希",
    "Control plane to edge sites": "控制平面到边缘站点",
    "Create a desired release for {site}. Nodes apply it independently and may still reject or roll back the change.": "为 {site} 创建目标发布。节点会独立应用，仍可能拒绝或回滚该变更。",
    "Current version": "当前版本",
    "DEPLOY TARGETS": "部署目标",
    "DRAFT": "草稿",
    "Drafts": "草稿",
    "Effective source CIDRs": "生效来源 CIDR",
    "Endpoint count": "出口数量",
    "Fetched": "获取时间",
    "Fetched {date}": "获取于 {date}",
    "Format": "格式",
    "HISTORY": "历史记录",
    "HTTP URL": "HTTP URL",
    "IMMUTABLE HISTORY": "不可变历史",
    "Import version": "导入版本",
    "Imported upstream": "导入的上游",
    "Importing...": "导入中...",
    "NODE RECONCILIATION": "节点协调",
    "Name": "名称",
    "No CIDRs supplied": "未提供 CIDR",
    "No edge node": "没有边缘节点",
    "Not refreshed": "未刷新",
    "Parsed": "解析状态",
    "Parsing did not produce usable outbounds.": "解析未生成可用出口。",
    "Previous release": "上一个发布",
    "Previous version": "上一个版本",
    "Publication": "发布状态",
    "Publish": "发布",
    "Publish to selected sites": "发布到所选站点",
    "Queue refresh": "加入刷新队列",
    "Queueing...": "排队中...",
    "READY TO PUBLISH": "待发布",
    "RELEASE": "发布",
    "Refresh interval": "刷新间隔",
    "Refresh {name}": "刷新 {name}",
    "Refreshed {date}": "刷新于 {date}",
    "Regional upstream": "区域上游",
    "Release did not complete": "发布未完成",
    "Release {version} to {count} selected sites. Each edge node validates and acknowledges the new outbound configuration independently.": "将 {version} 发布到 {count} 个所选站点。每个边缘节点会独立校验并确认新的出站配置。",
    "Remove CIDR": "移除 CIDR",
    "Restore the previous selected version for {site}. This creates a new release and waits for node ACKs.": "恢复 {site} 之前选定的版本。这会创建新的发布并等待节点 ACK。",
    "Revision v{revision} · {date}": "版本 v{revision} · {date}",
    "Risk": "风险",
    "Roll back {name}": "回滚 {name}",
    "SELECTED VERSION": "已选版本",
    "SITE SELECTIONS": "站点选择",
    "STRUCTURED DIFF": "结构化差异",
    "Sites": "站点",
    "Source": "来源",
    "Source revision v{revision} · expires {date}": "来源版本 v{revision} · 到期于 {date}",
    "Sources": "来源",
    "Subscription file": "订阅文件",
    "Targets": "目标节点",
    "UPSTREAMS": "上游",
    "Upload file": "上传文件",
    "Validation": "校验",
    "Version cannot be published": "该版本无法发布",
    "Versions": "版本记录",
    "{count} bytes": "{count} 字节",
    "{count} selected": "已选 {count} 个",
    "Regional proxy state and deployment activity.": "区域代理状态与部署活动。",
    "Heartbeat, configuration, and service facts from each monitor.": "每个监控器上报的心跳、配置和服务状态。",
    "Regional source access is defined once and applied to local edge nodes.": "区域来源访问统一定义，并应用到本地边缘节点。",
    "Temporary source access applies to all sites and expires automatically.": "临时来源访问适用于所有站点，并会自动过期。",
    "Source CIDRs from one site can be added to another site only through an explicit allow.": "一个站点的来源 CIDR 只能通过显式允许加入另一个站点。",
    "Blocked destination patterns are included in every generated bundle.": "被拒绝的目标规则会包含在每个生成的配置包中。",
    "Versioned upstream content is selected per site and released through the normal node ACK path.": "按站点选择带版本的上游内容，并通过正常的节点 ACK 流程发布。",
    "Draft, validate, publish, and reconcile every node independently.": "独立完成每个节点的草拟、校验、发布和协调。",
    "Queue state, retry history, and cancellation boundaries for control-plane work.": "控制平面工作的队列状态、重试历史和取消边界。",
    "Append-only control-plane events with a verifiable hash chain.": "具有可验证哈希链的仅追加控制平面事件。",
    "Employee proxy connection details and the rendered Linux setup script.": "员工代理连接详情和已生成的 Linux 安装脚本。",
    "Travel exceptions": "出差例外",
    "Cross-site access": "跨站点访问",
    "Cancel task": "取消任务",
    "Create rollback release": "创建回滚发布",
    "Enable access": "启用访问",
    "Enable cross-site access": "启用跨站点访问",
    "No active tasks": "没有活动任务",
    "No audit events recorded": "没有审计事件记录",
    "No publishable drafts": "没有可发布草稿",
    "No releases recorded": "没有发布记录",
    "No releases yet": "暂无发布",
    "No sites have a selected subscription": "没有站点选择订阅",
    "No subscription sources": "没有订阅来源",
    "No tasks recorded": "没有任务记录",
    "No versions for this source": "此来源没有版本",
    "Parsed versions are available after a refresh or file import.": "刷新或导入文件后可使用解析出的版本。",
    "Publish configuration draft": "发布配置草稿",
    "Publish release": "发布版本",
    "Publish subscription version": "发布订阅版本",
    "Publish version": "发布版本",
    "Queued and running jobs appear here.": "排队和运行中的作业会显示在这里。",
    "Refresh or import content to create an immutable version.": "刷新或导入内容以创建不可变版本。",
    "Remove destination": "移除目标规则",
    "Remove destination deny": "移除目标拒绝规则",
    "Remove exception": "移除例外",
    "Remove site CIDR": "移除站点 CIDR",
    "Remove travel exception": "移除出差例外",
    "Roll back site subscription": "回滚站点订阅",
    "Select a draft or release": "选择草稿或发布记录",
    "Select a source version": "选择来源版本",
    "Its diff and node reconciliation appear here.": "其差异和节点协调信息会显示在这里。",
    "Add an HTTP source or import a supported file.": "添加 HTTP 来源或导入受支持的文件。",
    "Create a draft from a site policy workspace.": "从站点策略工作区创建草稿。",
    "Unable to load exceptions.": "无法加载例外规则。",
    "Unable to load subscription state.": "无法加载订阅状态。",
    "The subscription operation was not accepted.": "订阅操作未被接受。",
    "Unable to load release state.": "无法加载发布状态。",
    "The release could not be created.": "无法创建发布。",
    "Release history is unavailable.": "发布历史不可用。",
    "Task queue is unavailable.": "任务队列不可用。",
    "ACK data is unavailable.": "ACK 数据不可用。",
    "Restore": "恢复",
    "Shutdown": "关闭",
    "Restore site listener": "恢复站点监听器",
    "Emergency shutdown": "紧急关闭",
    "Restore site": "恢复站点",
    "Shut down site": "关闭站点",
    "domain": "域名",
    "ip": "IP 地址",
    "cidr": "CIDR",
    "added": "已添加",
    "removed": "已移除",
    "subscription refresh": "订阅刷新",
    "config publish": "配置发布",
    "Central Region": "中部区域",
    "East Region": "东部区域",
    "North Region": "北部区域",
    "South Region": "南部区域",
    "West Region": "西部区域",
  },
  en: {},
  es: {
    "Password": "Contraseña",
    "GQuan code": "Código GQuan",
    "Create account": "Crear cuenta",
    "Reset password": "Restablecer contraseña",
    "Back to console": "Volver a la consola",
    "Control plane access": "Acceso al plano de control",
    "IT code": "Código IT",
    "Verification code": "Código de verificación",
    "Send code": "Enviar código",
    "Send again": "Reenviar",
    "Sending...": "Enviando...",
    "Working...": "Procesando...",
    "Sign in": "Iniciar sesión",
    "Sign in with code": "Iniciar con código",
    "New password": "Nueva contraseña",
    "Confirm password": "Confirmar contraseña",
    "Verify your IT code before setting a password.": "Verifica tu código IT antes de establecer una contraseña.",
    "Verify your IT code before choosing a new password.": "Verifica tu código IT antes de elegir una nueva contraseña.",
    "Verification code sent through GQuan.": "El código se envió por GQuan.",
    "Account registered. Sign in with the password you set.": "Cuenta registrada. Inicia sesión con la contraseña creada.",
    "Password reset. Sign in with the new password.": "Contraseña restablecida. Inicia sesión con la nueva contraseña.",
    "No active account is registered for this IT code.": "No hay una cuenta activa para este código IT.",
    "GQuan verification delivery is unavailable.": "El envío de verificación GQuan no está disponible.",
    "GQuan did not accept the verification request.": "GQuan no aceptó la solicitud de verificación.",
    "GQuan verification quota is currently exhausted.": "La cuota de verificación GQuan está agotada.",
    "The IT code or password is not valid.": "El código IT o la contraseña no son válidos.",
    "Enter a valid IT code.": "Introduce un código IT válido.",
    "Passwords must contain at least 12 characters.": "La contraseña debe tener al menos 12 caracteres.",
    "This IT code already has an account.": "Este código IT ya tiene una cuenta.",
    "The password confirmation does not match.": "La confirmación de contraseña no coincide.",
    "This code can no longer be used. Request another one.": "Este código ya no se puede usar. Solicita otro.",
    "This verification code has expired. Request another one.": "Este código ha caducado. Solicita otro.",
    "The verification code is not valid.": "El código de verificación no es válido.",
    "A code was sent recently. Wait before requesting another.": "Se envió un código hace poco. Espera antes de solicitar otro.",
    "Unable to reach the control plane. Check the local service and retry.": "No se puede conectar al plano de control. Comprueba el servicio local e inténtalo de nuevo.",
    "The request contains invalid fields.": "La solicitud contiene campos no válidos.",
    "The request could not be completed.": "No se pudo completar la solicitud.",
    "Language": "Idioma",
    "Switch to dark mode": "Cambiar a modo oscuro",
    "Switch to light mode": "Cambiar a modo claro",
    "Close dialog": "Cerrar diálogo",
    "Close details": "Cerrar detalles",
    "Close navigation": "Cerrar navegación",
    "Open navigation": "Abrir navegación",
    "Refresh workspace": "Actualizar espacio de trabajo",
    "Sign out": "Cerrar sesión",
    "Primary navigation": "Navegación principal",
    "OPERATE": "OPERAR",
    "POLICY": "POLÍTICA",
    "DEPLOY": "DESPLIEGUE",
    "GOVERN": "GOBIERNO",
    "Overview": "Resumen",
    "Nodes": "Nodos",
    "Sites & CIDRs": "Sitios y CIDR",
    "Exceptions": "Excepciones",
    "Cross-site": "Entre sitios",
    "Destination deny": "Denegación de destino",
    "Subscriptions": "Suscripciones",
    "Releases": "Versiones",
    "Tasks": "Tareas",
    "Audit": "Auditoría",
    "Access": "Acceso",
    "Control plane": "Plano de control",
    "HTTP only": "Solo HTTP",
    "Employee path": "Ruta de empleado",
    "Sign in required": "Inicio de sesión requerido",
    "Use a control-plane administrator account to load operational data.": "Usa una cuenta administradora para cargar los datos operativos.",
    "Unable to load this workspace": "No se puede cargar este espacio de trabajo",
    "Retry": "Reintentar",
    "Loading": "Cargando",
    "enabled": "habilitado",
    "disabled": "deshabilitado",
    "online": "en línea",
    "offline": "sin conexión",
    "active": "activo",
    "shutdown": "apagado",
    "in sync": "sincronizado",
    "drift": "desviación",
    "pending": "pendiente",
    "running": "en ejecución",
    "succeeded": "completado",
    "failed": "fallido",
    "queued": "en cola",
    "ready": "listo",
    "published": "publicado",
    "current": "actual",
    "valid": "válido",
    "allowed": "permitido",
    "denied": "denegado",
    "Authentication method": "Método de autenticación",
    "Account actions": "Acciones de cuenta",
    "Cancel": "Cancelar",
    "OPERATIONS": "OPERACIONES",
    "SITE POLICY": "POLÍTICA DEL SITIO",
    "REGIONAL TOPOLOGY": "TOPOLOGÍA REGIONAL",
    "DEPLOYMENT": "DESPLIEGUE",
    "EDGE INVENTORY": "INVENTARIO PERIMETRAL",
    "TASK QUEUE": "COLA DE TAREAS",
    "CURRENT PATH": "RUTA ACTUAL",
    "DEFAULT DENY": "DENEGAR POR DEFECTO",
    "SOURCE ACCESS": "ACCESO DE ORIGEN",
    "POLICY TEST": "PRUEBA DE POLÍTICA",
    "Actions": "Acciones",
    "Action": "Acción",
    "Actor": "Actor",
    "Add": "Añadir",
    "Adding...": "Añadiendo...",
    "Add CIDR": "Añadir CIDR",
    "Add destination": "Añadir destino",
    "Add exception": "Añadir excepción",
    "Add HTTP source": "Añadir origen HTTP",
    "Advertise IP": "IP anunciada",
    "After": "Después",
    "All states": "Todos los estados",
    "Applied / desired": "Aplicado / deseado",
    "Applied bundle matches": "El paquete aplicado coincide",
    "Applied hash": "Hash aplicado",
    "Audit event": "Evento de auditoría",
    "Audit chain is valid": "La cadena de auditoría es válida",
    "Audit chain verification failed": "Falló la verificación de la cadena de auditoría",
    "Before": "Antes",
    "Chain origin": "Origen de la cadena",
    "Check access": "Comprobar acceso",
    "Checking...": "Comprobando...",
    "CIDR is the current access boundary.": "El CIDR es el límite de acceso actual.",
    "CIDR or IP": "CIDR o IP",
    "Column: destination listener": "Columna: escucha de destino",
    "Comment": "Comentario",
    "Config": "Configuración",
    "Configuration": "Configuración",
    "Configuration in sync": "Configuración sincronizada",
    "Configuration or service state differs from the desired release.": "El estado de configuración o servicio difiere de la versión deseada.",
    "Control-plane summary": "Resumen del plano de control",
    "Copied": "Copiado",
    "Copy": "Copiar",
    "Create draft": "Crear borrador",
    "Created": "Creado",
    "Delete destination": "Eliminar destino",
    "Delete exception": "Eliminar excepción",
    "Details": "Detalles",
    "Disabled": "Desactivado",
    "Domain": "Dominio",
    "Download": "Descargar",
    "Drift or failure": "Desviación o fallo",
    "Edge nodes": "Nodos perimetrales",
    "Enter an address to calculate the effective access policy.": "Introduce una dirección para calcular la política de acceso efectiva.",
    "Error": "Error",
    "Expires": "Caduca",
    "Expires at": "Caduca el",
    "Filter node status": "Filtrar estado de nodo",
    "From \\ To": "Origen \\ Destino",
    "HTTPS proxy listener": "Escucha de proxy HTTPS",
    "Hash": "Hash",
    "Heartbeat": "Latido",
    "Heartbeat state": "Estado del latido",
    "IP address": "Dirección IP",
    "Immutable hash": "Hash inmutable",
    "Inspect": "Inspeccionar",
    "Invalid source IP.": "La IP de origen no es válida.",
    "Last error": "Último error",
    "Last heartbeat": "Último latido",
    "Lease": "Concesión",
    "Listener": "Escucha",
    "Liveness": "Disponibilidad",
    "Manage policy": "Gestionar política",
    "Monitor": "Monitor",
    "Needs attention": "Requiere atención",
    "No active exceptions.": "No hay excepciones activas.",
    "No destinations are blocked.": "No hay destinos bloqueados.",
    "No effective CIDRs": "No hay CIDR efectivos",
    "No node enrolled": "No hay nodos registrados",
    "No site CIDRs configured.": "No hay CIDR configurados para el sitio.",
    "Node": "Nodo",
    "Node inventory": "Inventario de nodos",
    "Node state": "Estado de nodo",
    "Nodes online": "Nodos en línea",
    "Office network": "Red de oficina",
    "Offline": "Sin conexión",
    "Online": "En línea",
    "Open nodes": "Abrir nodos",
    "Open policy": "Abrir política",
    "Open queue": "Abrir cola",
    "Operator name": "Nombre del operador",
    "Owner": "Propietario",
    "Pattern": "Patrón",
    "Policy changes require a release before nodes apply them.": "Los cambios de política requieren una versión antes de que los nodos los apliquen.",
    "Policy revision": "Revisión de política",
    "Previous hash": "Hash anterior",
    "Progress": "Progreso",
    "Proxy port": "Puerto de proxy",
    "Reason for block": "Motivo del bloqueo",
    "Recent releases": "Versiones recientes",
    "Request": "Solicitud",
    "Requires operator review": "Requiere revisión del operador",
    "Result": "Resultado",
    "Retries": "Reintentos",
    "Review nodes": "Revisar nodos",
    "Row: source site": "Fila: sitio de origen",
    "Sensitive values are redacted before storage.": "Los valores sensibles se ocultan antes de almacenarse.",
    "Service": "Servicio",
    "Setup script": "Script de configuración",
    "Site": "Sitio",
    "Site CIDRs": "CIDR del sitio",
    "Site authentication is also required.": "También se requiere autenticación del sitio.",
    "Site topology": "Topología del sitio",
    "Source IP": "IP de origen",
    "Source IP preview": "Vista previa de IP de origen",
    "Source-to-destination matrix": "Matriz de origen a destino",
    "State": "Estado",
    "Subscription": "Suscripción",
    "Target": "Destino",
    "Task": "Tarea",
    "Time": "Hora",
    "Travel approval reference": "Referencia de aprobación de viaje",
    "Type": "Tipo",
    "Unknown site": "Sitio desconocido",
    "Updated": "Actualizado",
    "Verify chain": "Verificar cadena",
    "Verifying...": "Verificando...",
    "Version": "Versión",
    "View": "Ver",
    "View all": "Ver todo",
    "this CIDR": "este CIDR",
    "this exception": "esta excepción",
    "this pattern": "este patrón",
    "this task": "esta tarea",
    "node": "nodo",
    "nodes": "nodos",
    "healthy": "correcto",
    "degraded": "degradado",
    "attention": "requiere atención",
    "not enrolled": "no registrado",
    "unhealthy": "no saludable",
    "rollback failed": "reversión fallida",
    "applying": "aplicando",
    "health check": "comprobación de estado",
    "rolling back": "revirtiendo",
    "rolled back": "revertido",
    "cancel requested": "cancelación solicitada",
    "expired": "caducado",
    "high": "alto",
    "medium": "medio",
    "low": "bajo",
    "draft": "borrador",
    "validated": "validado",
    "release": "versión",
    "{action} {name}": "{action} {name}",
    "{count} events": "{count} eventos",
    "{count} events checked": "{count} eventos comprobados",
    "{count} local policy changes included in the next draft.": "El próximo borrador incluye {count} cambios de política locales.",
    "{count} nodes": "{count} nodos",
    "{count} nodes need attention": "{count} nodos requieren atención",
    "{count} queued or running tasks": "{count} tareas en cola o en ejecución",
    "{count} sites": "{count} sitios",
    "{name} CIDRs": "CIDR de {name}",
    "Policy revision v{revision} · HTTP :{port}": "Revisión v{revision} · HTTP :{port}",
    "Allow {from} CIDRs to access {to}": "Permitir que los CIDR de {from} accedan a {to}",
    "Add {from} source CIDRs to the effective access policy for {to}. This expands the destination listener's allowed network scope.": "Añade los CIDR de origen de {from} a la política de acceso efectiva de {to}. Esto amplía el ámbito de red permitido de la escucha de destino.",
    "Block the proxy listener for {name}. This changes desired policy and requires a release to reach its edge nodes.": "Bloquea la escucha de proxy de {name}. Esto cambia la política deseada y requiere una versión para llegar a los nodos perimetrales.",
    "Restore proxy listener access for {name}. A release is still required for monitors to apply the state.": "Restaura el acceso a la escucha de proxy de {name}. Los monitores aún necesitan una versión para aplicar el estado.",
    "Delete {value}": "Eliminar {value}",
    "Remove {value}": "Quitar {value}",
    "Remove {value}. The next release for each site will exclude it from effective source access.": "Quita {value}. La próxima versión de cada sitio lo excluirá del acceso de origen efectivo.",
    "Remove {value} from the global deny policy. New releases will no longer include it.": "Quita {value} de la política global de denegación. Las nuevas versiones dejarán de incluirlo.",
    "Remove {cidr} from {site}. The change remains local to the control plane until a release succeeds.": "Quita {cidr} de {site}. El cambio permanece local en el plano de control hasta que una versión se complete.",
    "Request cancellation for {task}. Running work stops at its next safe checkpoint.": "Solicita cancelar {task}. El trabajo en curso se detiene en su siguiente punto seguro.",
    "Destination HTTPS remains end-to-end inside the HTTP CONNECT tunnel.": "El HTTPS de destino se mantiene de extremo a extremo dentro del túnel HTTP CONNECT.",
    "The control plane did not respond.": "El plano de control no respondió.",
    "Unable to load sites.": "No se pueden cargar los sitios.",
    "Unable to load CIDRs.": "No se pueden cargar los CIDR.",
    "This site does not exist.": "Este sitio no existe.",
    "The policy change was not accepted.": "No se aceptó el cambio de política.",
    "The exception was not accepted.": "No se aceptó la excepción.",
    "The cross-site policy was not accepted.": "No se aceptó la política entre sitios.",
    "The destination policy was not accepted.": "No se aceptó la política de destino.",
    "Unable to load cross-site access.": "No se puede cargar el acceso entre sitios.",
    "Unable to load the destination deny list.": "No se puede cargar la lista de denegación de destino.",
    "Unable to load tasks.": "No se pueden cargar las tareas.",
    "The task could not be cancelled.": "No se pudo cancelar la tarea.",
    "Audit verification failed.": "Falló la verificación de auditoría.",
    "Unable to load audit events.": "No se pueden cargar los eventos de auditoría.",
    "Unable to render the Linux setup script.": "No se puede generar el script de configuración de Linux.",
    "network_error": "No se puede conectar al plano de control.",
    "request_failed": "No se pudo completar la solicitud.",
    "invalid_cidr": "El CIDR no es válido.",
    "cidr_exists": "Ese CIDR ya existe.",
    "invalid_source_ip": "La IP de origen no es válida.",
    "exception_must_expire_in_future": "La excepción debe caducar en el futuro.",
    "invalid_exception": "La excepción no es válida.",
    "invalid_blacklist_pattern": "El patrón de destino no es válido.",
    "blacklist_entry_exists": "Ese patrón de destino ya existe.",
    "1 hour": "1 hora",
    "6 hours": "6 horas",
    "24 hours": "24 horas",
    "ACK status": "Estado de ACK",
    "Active deployments": "Despliegues activos",
    "Active work": "Trabajo activo",
    "Awaiting node ACK": "Esperando ACK del nodo",
    "Content hash": "Hash de contenido",
    "Control plane to edge sites": "Del plano de control a sitios perimetrales",
    "Create a desired release for {site}. Nodes apply it independently and may still reject or roll back the change.": "Crea una versión deseada para {site}. Los nodos la aplican de forma independiente y aún pueden rechazar o revertir el cambio.",
    "Current version": "Versión actual",
    "DEPLOY TARGETS": "OBJETIVOS DE DESPLIEGUE",
    "DRAFT": "BORRADOR",
    "Drafts": "Borradores",
    "Effective source CIDRs": "CIDR de origen efectivos",
    "Endpoint count": "Cantidad de extremos",
    "Fetched": "Obtenido",
    "Fetched {date}": "Obtenido {date}",
    "Format": "Formato",
    "HISTORY": "HISTORIAL",
    "HTTP URL": "URL HTTP",
    "IMMUTABLE HISTORY": "HISTORIAL INMUTABLE",
    "Import version": "Importar versión",
    "Imported upstream": "Origen ascendente importado",
    "Importing...": "Importando...",
    "NODE RECONCILIATION": "CONCILIACIÓN DE NODOS",
    "Name": "Nombre",
    "No CIDRs supplied": "No se proporcionaron CIDR",
    "No edge node": "Sin nodo perimetral",
    "Not refreshed": "Sin actualizar",
    "Parsed": "Analizado",
    "Parsing did not produce usable outbounds.": "El análisis no produjo salidas utilizables.",
    "Previous release": "Versión anterior",
    "Previous version": "Versión anterior",
    "Publication": "Publicación",
    "Publish": "Publicar",
    "Publish to selected sites": "Publicar en los sitios seleccionados",
    "Queue refresh": "Poner actualización en cola",
    "Queueing...": "Poniendo en cola...",
    "READY TO PUBLISH": "LISTO PARA PUBLICAR",
    "RELEASE": "VERSIÓN",
    "Refresh interval": "Intervalo de actualización",
    "Refresh {name}": "Actualizar {name}",
    "Refreshed {date}": "Actualizado {date}",
    "Regional upstream": "Origen ascendente regional",
    "Release did not complete": "La versión no se completó",
    "Release {version} to {count} selected sites. Each edge node validates and acknowledges the new outbound configuration independently.": "Publica {version} en {count} sitios seleccionados. Cada nodo perimetral valida y confirma de forma independiente la nueva configuración de salida.",
    "Remove CIDR": "Quitar CIDR",
    "Restore the previous selected version for {site}. This creates a new release and waits for node ACKs.": "Restaura la versión seleccionada anterior de {site}. Esto crea una nueva versión y espera los ACK de nodos.",
    "Revision v{revision} · {date}": "Revisión v{revision} · {date}",
    "Risk": "Riesgo",
    "Roll back {name}": "Revertir {name}",
    "SELECTED VERSION": "VERSIÓN SELECCIONADA",
    "SITE SELECTIONS": "SELECCIONES DE SITIO",
    "STRUCTURED DIFF": "DIFERENCIA ESTRUCTURADA",
    "Sites": "Sitios",
    "Source": "Origen",
    "Source revision v{revision} · expires {date}": "Revisión de origen v{revision} · caduca {date}",
    "Sources": "Orígenes",
    "Subscription file": "Archivo de suscripción",
    "Targets": "Objetivos",
    "UPSTREAMS": "ORÍGENES ASCENDENTES",
    "Upload file": "Subir archivo",
    "Validation": "Validación",
    "Version cannot be published": "La versión no se puede publicar",
    "Versions": "Versiones",
    "{count} bytes": "{count} bytes",
    "{count} selected": "{count} seleccionados",
    "Regional proxy state and deployment activity.": "Estado regional del proxy y actividad de despliegue.",
    "Heartbeat, configuration, and service facts from each monitor.": "Datos de latido, configuración y servicio de cada monitor.",
    "Regional source access is defined once and applied to local edge nodes.": "El acceso de origen regional se define una vez y se aplica a los nodos perimetrales locales.",
    "Temporary source access applies to all sites and expires automatically.": "El acceso de origen temporal se aplica a todos los sitios y caduca automáticamente.",
    "Source CIDRs from one site can be added to another site only through an explicit allow.": "Los CIDR de origen de un sitio solo pueden añadirse a otro mediante una autorización explícita.",
    "Blocked destination patterns are included in every generated bundle.": "Los patrones de destino bloqueados se incluyen en cada paquete generado.",
    "Versioned upstream content is selected per site and released through the normal node ACK path.": "El contenido ascendente versionado se selecciona por sitio y se publica por la ruta normal de ACK de nodos.",
    "Draft, validate, publish, and reconcile every node independently.": "Crea borradores, valida, publica y concilia cada nodo de forma independiente.",
    "Queue state, retry history, and cancellation boundaries for control-plane work.": "Estado de cola, historial de reintentos y límites de cancelación para el trabajo del plano de control.",
    "Append-only control-plane events with a verifiable hash chain.": "Eventos del plano de control solo anexables con una cadena de hash verificable.",
    "Employee proxy connection details and the rendered Linux setup script.": "Detalles de conexión proxy para empleados y el script de configuración de Linux generado.",
    "Travel exceptions": "Excepciones de viaje",
    "Cross-site access": "Acceso entre sitios",
    "Cancel task": "Cancelar tarea",
    "Create rollback release": "Crear versión de reversión",
    "Enable access": "Habilitar acceso",
    "Enable cross-site access": "Habilitar acceso entre sitios",
    "No active tasks": "No hay tareas activas",
    "No audit events recorded": "No hay eventos de auditoría registrados",
    "No publishable drafts": "No hay borradores publicables",
    "No releases recorded": "No hay versiones registradas",
    "No releases yet": "Aún no hay versiones",
    "No sites have a selected subscription": "Ningún sitio tiene una suscripción seleccionada",
    "No subscription sources": "No hay orígenes de suscripción",
    "No tasks recorded": "No hay tareas registradas",
    "No versions for this source": "No hay versiones para este origen",
    "Parsed versions are available after a refresh or file import.": "Las versiones analizadas están disponibles después de actualizar o importar un archivo.",
    "Publish configuration draft": "Publicar borrador de configuración",
    "Publish release": "Publicar versión",
    "Publish subscription version": "Publicar versión de suscripción",
    "Publish version": "Publicar versión",
    "Queued and running jobs appear here.": "Los trabajos en cola y en ejecución aparecen aquí.",
    "Refresh or import content to create an immutable version.": "Actualiza o importa contenido para crear una versión inmutable.",
    "Remove destination": "Quitar destino",
    "Remove destination deny": "Quitar denegación de destino",
    "Remove exception": "Quitar excepción",
    "Remove site CIDR": "Quitar CIDR del sitio",
    "Remove travel exception": "Quitar excepción de viaje",
    "Roll back site subscription": "Revertir suscripción del sitio",
    "Select a draft or release": "Selecciona un borrador o versión",
    "Select a source version": "Selecciona una versión de origen",
    "Its diff and node reconciliation appear here.": "Su diferencia y conciliación de nodos aparecen aquí.",
    "Add an HTTP source or import a supported file.": "Añade un origen HTTP o importa un archivo compatible.",
    "Create a draft from a site policy workspace.": "Crea un borrador desde el espacio de trabajo de política del sitio.",
    "Unable to load exceptions.": "No se pueden cargar las excepciones.",
    "Unable to load subscription state.": "No se puede cargar el estado de suscripción.",
    "The subscription operation was not accepted.": "No se aceptó la operación de suscripción.",
    "Unable to load release state.": "No se puede cargar el estado de versión.",
    "The release could not be created.": "No se pudo crear la versión.",
    "Release history is unavailable.": "El historial de versiones no está disponible.",
    "Task queue is unavailable.": "La cola de tareas no está disponible.",
    "ACK data is unavailable.": "Los datos ACK no están disponibles.",
    "Restore": "Restaurar",
    "Shutdown": "Apagar",
    "Restore site listener": "Restaurar escucha del sitio",
    "Emergency shutdown": "Apagado de emergencia",
    "Restore site": "Restaurar sitio",
    "Shut down site": "Apagar sitio",
    "domain": "dominio",
    "ip": "dirección IP",
    "cidr": "CIDR",
    "added": "añadido",
    "removed": "eliminado",
    "subscription refresh": "actualización de suscripción",
    "config publish": "publicación de configuración",
    "Central Region": "Región central",
    "East Region": "Región este",
    "North Region": "Región norte",
    "South Region": "Región sur",
    "West Region": "Región oeste",
  },
};

function translate(locale: Locale, key: string, values?: Values) {
  let message = messages[locale][key] || key;
  for (const [name, value] of Object.entries(values || {})) {
    message = message.replaceAll(`{${name}}`, String(value));
  }
  return message;
}

type PreferencesContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  t: (key: string, values?: Values) => string;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

export function PreferencesProvider({ children }: PropsWithChildren) {
  const [locale, setLocale] = useState<Locale>("zh-CN");
  const [theme, setTheme] = useState<Theme>("light");

  useEffect(() => {
    const savedLocale = window.localStorage.getItem(localeStorageKey);
    const savedTheme = window.localStorage.getItem(themeStorageKey);
    if (savedLocale === "zh-CN" || savedLocale === "en" || savedLocale === "es") {
      setLocale(savedLocale);
    }
    if (savedTheme === "light" || savedTheme === "dark") {
      setTheme(savedTheme);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = locale;
    window.localStorage.setItem(localeStorageKey, locale);
  }, [locale]);

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    document.documentElement.style.colorScheme = theme;
    window.localStorage.setItem(themeStorageKey, theme);
  }, [theme]);

  const value = useMemo<PreferencesContextValue>(
    () => ({ locale, setLocale, theme, setTheme, t: (key, values) => translate(locale, key, values) }),
    [locale, theme],
  );

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error("usePreferences must be used within PreferencesProvider");
  return context;
}
